import { model } from "@medusajs/framework/utils"

const TaxInvoice = model.define("tax_invoice", {
  id: model.id().primaryKey(),
  invoice_number: model.text(),
  invoice_type: model.enum(["tax_invoice", "simplified_invoice", "proforma", "credit_note", "debit_note"]),
  shop_id: model.text(),
  sale_id: model.text().nullable(),
  customer_id: model.text().nullable(),
  tims_enabled: model.boolean().default(false),
  tims_invoice_id: model.text().nullable(),
  tims_control_unit_serial: model.text().nullable(),
  tims_react_code: model.text().nullable(),
  tims_transmission_status: model.enum(["pending", "transmitted", "accepted", "rejected"]).default("pending"),
  tims_transmitted_at: model.dateTime().nullable(),
  tims_accepted_at: model.dateTime().nullable(),
  tims_rejection_reason: model.text().nullable(),
  supplier_kra_pin: model.text().nullable(),
  supplier_name: model.text(),
  supplier_address: model.text().nullable(),
  supplier_vat_number: model.text().nullable(),
  customer_kra_pin: model.text().nullable(),
  customer_name: model.text().nullable(),
  customer_address: model.text().nullable(),
  customer_vat_number: model.text().nullable(),
  subtotal: model.bigNumber().default(0),
  discount_amount: model.bigNumber().default(0),
  taxable_amount: model.bigNumber().default(0),
  vat_rate: model.number().default(16),
  vat_amount: model.bigNumber().default(0),
  withholding_vat_amount: model.bigNumber().default(0),
  excise_duty_amount: model.bigNumber().default(0),
  total_amount: model.bigNumber().default(0),
  vat_breakdown: model.json().nullable(),
  items: model.json(),
  payment_status: model.enum(["paid", "partial", "unpaid", "credit"]).default("paid"),
  payment_method: model.text().nullable(),
  payment_date: model.dateTime().nullable(),
  invoice_date: model.dateTime(),
  supply_date: model.dateTime(),
  due_date: model.dateTime().nullable(),
  original_invoice_number: model.text().nullable(),
  credit_note_reason: model.text().nullable(),
  qr_code_data: model.text().nullable(),
  qr_code_image_url: model.text().nullable(),
  status: model.enum(["draft", "issued", "transmitted", "accepted", "cancelled", "void"]).default("issued"),
  cancelled_at: model.dateTime().nullable(),
  cancellation_reason: model.text().nullable(),
  created_by: model.text().nullable(),
})

export default TaxInvoice
