import { model } from "@medusajs/framework/utils"

const VatReturn = model.define("vat_return", {
  id: model.id().primaryKey(),
  return_period: model.text(),
  shop_id: model.text(),
  kra_pin: model.text().nullable(),
  standard_rated_sales: model.bigNumber().default(0),
  standard_rated_vat: model.bigNumber().default(0),
  reduced_rated_sales: model.bigNumber().default(0),
  reduced_rated_vat: model.bigNumber().default(0),
  zero_rated_sales: model.bigNumber().default(0),
  exempt_sales: model.bigNumber().default(0),
  total_output_vat: model.bigNumber().default(0),
  standard_rated_purchases: model.bigNumber().default(0),
  standard_rated_input_vat: model.bigNumber().default(0),
  capital_goods_input_vat: model.bigNumber().default(0),
  total_input_vat: model.bigNumber().default(0),
  withholding_vat_suffered: model.bigNumber().default(0),
  withholding_vat_certificate: model.text().nullable(),
  vat_payable: model.bigNumber().default(0),
  vat_refundable: model.bigNumber().default(0),
  previous_period_adjustments: model.bigNumber().default(0),
  other_adjustments: model.bigNumber().default(0),
  adjustments_description: model.text().nullable(),
  filed_via: model.enum(["manual", "itimis", "api"]).default("manual"),
  itimis_acknowledgement: model.text().nullable(),
  filed_at: model.dateTime().nullable(),
  filed_by: model.text().nullable(),
  payment_status: model.enum(["pending", "paid", "partial", "refund_due"]).default("pending"),
  payment_reference: model.text().nullable(),
  payment_date: model.dateTime().nullable(),
  payment_amount: model.bigNumber().nullable(),
  status: model.enum(["draft", "filed", "accepted", "rejected", "amended"]).default("draft"),
  rejection_reason: model.text().nullable(),
  amended_return_id: model.text().nullable(),
  supporting_documents: model.json().nullable(),
})

export default VatReturn
