import { model } from "@medusajs/framework/utils"

const AiConfig = model.define("ai_config", {
  id: model.id().primaryKey(),
  scope: model.enum(["platform", "shop"]).default("platform"),
  shop_id: model.text().nullable(),
  litellm_base_url: model.text().default("http://localhost:4000"),
  litellm_api_key: model.text().nullable(),
  default_provider: model.text().default("openai"),
  default_model: model.text().default("gpt-3.5-turbo"),
  provider_options: model.json().nullable(),
  model_options: model.json().nullable(),
  fallback_models: model.json().nullable(),
  max_tokens_per_request: model.number().default(500),
  max_tokens_per_day: model.number().default(10000),
  max_cost_per_day: model.bigNumber().nullable(),
  preferred_tier: model.enum(["budget", "balanced", "premium"]).default("budget"),
  intent_rules: model.json().nullable(),
  escalation_rules: model.json().nullable(),
  chatbot_enabled: model.boolean().default(true),
  chatbot_personality: model
    .enum(["friendly", "professional", "casual", "formal"])
    .default("friendly"),
  chatbot_language: model.enum(["en", "sw", "both"]).default("both"),
  chatbot_welcome_message: model.text().nullable(),
  rag_enabled: model.boolean().default(true),
  ragflow_enabled: model.boolean().default(false),
  ragflow_base_url: model.text().nullable(),
  ragflow_api_key: model.text().nullable(),
  ragflow_knowledge_base_id: model.text().nullable(),
  embedding_model: model.text().default("text-embedding-3-small"),
  embedding_dimensions: model.number().default(1536),
  similarity_threshold: model.bigNumber().default(0.7),
  max_context_items: model.number().default(5),
  embed_products: model.boolean().default(true),
  embed_orders: model.boolean().default(false),
  embed_policies: model.boolean().default(true),
  embed_faqs: model.boolean().default(true),
  upload_receipts: model.boolean().default(true),
  upload_invoices: model.boolean().default(true),
  upload_catalogs: model.boolean().default(false),
  auto_embed_on_create: model.boolean().default(true),
  auto_embed_on_update: model.boolean().default(true),
  batch_embed_interval_hours: model.number().default(24),
  cache_embeddings: model.boolean().default(true),
  cache_ttl_hours: model.number().default(24),
  max_embeddings_per_day: model.number().default(1000),
  embeddings_today: model.number().default(0),
  recommendations_enabled: model.boolean().default(true),
  recommendations_algorithm: model
    .enum(["rules_only", "ai_only", "hybrid"])
    .default("hybrid"),
  recommendations_cache_hours: model.number().default(24),
  inventory_ai_enabled: model.boolean().default(true),
  pricing_ai_enabled: model.boolean().default(true),
  marketing_ai_enabled: model.boolean().default(true),
  analytics_ai_enabled: model.boolean().default(true),
  total_tokens_used: model.number().default(0),
  total_cost: model.bigNumber().default(0),
  last_reset_at: model.dateTime().nullable(),
  is_active: model.boolean().default(true),
})

export default AiConfig
